version: '3'

services:
  postgre:
    container_name: 'brBatel_base'
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: brBatel_password
      POSTGRES_USER: brBatel_user
      POSTGRES_DB: brBatel_database
    ports:
      - '5454:5432'
    expose:
      - '5454'
    #command: bash -c "yarn typeorm migration:run && yarn dev"
