version: '3'

services:
  postgre:
    container_name: 'brBatel_base'
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: brBatel_password
      POSTGRES_USER: brBatel_user
      POSTGRES_DB: brBatel_database
    ports:
      - '5454:5432'
    expose:
      - '5454'
  app:
    container_name: app_node_solid
    depends_on:
      - postgre
    build: .
    ports:
      - '3001:3335'
    command: yarn dev
    expose:
      - '3001'
    #command: bash -c "yarn typeorm migration:run && yarn dev"
